version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: koheitorres
        POSGRES_DB: postgres
    volumes:
      - /work/Sol-SubStream/docker/pgdata:/var/lib/postgresql/data/